### ISSUE TITLE
Repo description (not README.MD) says "HitHub"

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [Thomas-Mewily/Hello-World#1]
Just to let you know, in case you haven't noticed, the repository description (on the right side in the code tab, under about) says "Hithub". I'm pretty sure you meant "Github".

**Comment by Thomas-Mewily** [comment]
Fixed x)
Well seen too.
I don't have any interesting project shared to (my java project are probably the more "*complex*" one I made, and they are not that complex)
